### ISSUE TITLE
.exe Not Running

### ISSUE THREAD

**Issue by Sevenyx** [merlinfuchs/embed-generator#95]
I'm attempting a self-host, and have done each step successfully, but when it comes to running the exe, it just pops up for a split second and then crashes immediately. I have no idea what I'm doing wrong because, when I start the development servers manually, it works perfectly; I can create embeds and send them to my server, it all works very well... but I assume the exe is supposed to be a shortcut for having to run those commands myself? I've tried 3 separate installs and I keep coming up short on the very last step of running the exe. Any help would be super appreciated.

**Comment by merlinfuchs** [comment]
I would guess this is because you haven't configured the server correctly or the config isn't loaded. Because windows instantly closes the windows once it crashes it's really hard to debug ...

You can start the exe from the CMD using `start embedg.exe`. This should give you a chance to see the error message because the window isn't closed automatically.
